# Generated by Django 4.2.5 on 2024-01-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('OrderId', models.IntegerField(default=0)),
                ('InActive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VideoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('Description', models.CharField(blank=True, max_length=1500)),
                ('InActive', models.BooleanField(default=False)),
                ('Thumbnail', models.CharField(blank=True, default='', max_length=150)),
                ('VideoFile', models.FileField(blank=True, upload_to='video/')),
                ('Categories', models.ManyToManyField(to='mainapp.category')),
            ],
        ),
    ]
