version: '3'

services:
  django:
    container_name: video_catalog_app
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
      - django-media:/app/media

  nginx:
    container_name: video_catalog_nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - django
    volumes:
      - django-media:/app/media

volumes:
  django-media:
